{{- if .Values.knativeDeploy }}
{{- else }}
{{- range $name, $val := .Values.brand }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" $ }}-{{ $name }}"
  labels:
    draft: {{ default "draft-app" $.Values.draft }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" $.Values.draft }}
        name: "{{ template "fullname" $ }}-{{ $name }}"
{{- if $.Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ $.Chart.Name }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
{{- range $pkey, $pval := $.Values.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
{{- end }}
        - name: {{ $.Values.key }}
          value: {{ quote $val.ios.key_file }}
        volumeMounts:
        - name: "{{ template "fullname" $ }}-{{ $name }}"
          mountPath: {{ $.Values.config_dir }}
        ports:
        - containerPort: {{ $.Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ $.Values.probePath }}
            port: {{ $.Values.service.internalPort }}
          initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
          successThreshold: {{ $.Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ $.Values.probePath }}
            port: {{ $.Values.service.internalPort }}
          periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
          successThreshold: {{ $.Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ $.Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml $.Values.resources | indent 12 }}
      volumes:
      - name: "{{ template "fullname" $ }}-{{ $name }}"
        configMap:
          name: "{{ template "fullname" $ }}-{{ $name }}"
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
{{- end }}
{{- end }}
